// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface ImcViewController: UIViewController
-(IBAction) awakeFromNib;
-(IBAction) viewDidLoad;
-(IBAction) custom_title;
-(IBAction) custom_description;
-(IBAction) custom_imc;
-(IBAction) custom_imc_category;

@end

@interface PersonViewController: UIViewController
-(IBAction) viewDidLoad;

@end

